/* eslint-disable no-unused-vars */
process.on('uncaughtException', () => {
  // do nothing - this will prevent the Error below from closing this process
});

class Some {
  two(name) {
    throw new Error('Enough!');
  }
}

function one(name) {
  const arr = [1, '2', null];
  const obj = {
    name,
    num: 5,
  };
  const bool = false;
  const num = 0;
  const str = '';
  const something = undefined;
  const somethingElse = null;

  const ty = new Some();

  ty.two(name);
}

setTimeout(() => {
  one('some name');
}, 1000);
